source "http://rubygems.org"

gem 'nokogiri', '1.8.4'
gem "factory_bot"
gem "rufus-lru"
gem "net-http-persistent"
gem "multipart-post"
gem 'concurrent-ruby', '1.1.4'

group :development do
  gem 'mocha'
end
